# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
# use_modular_headers!

source 'https://github.com/CocoaPods/Specs.git'

project 'ClickStream.xcodeproj'
workspace 'ClickStream.xcworkspace'

def clickstream_pods
  pod 'Starscream', '~> 4.0.4'
  pod 'SwiftProtobuf', '~> 1.10.2'
  pod 'ReachabilitySwift'
  pod 'GRDB.swift', '5.12.0'
end

target 'ClickStream' do
  clickstream_pods
end

target 'ClickStreamTests' do
  clickstream_pods
end

target 'ClickStreamHost' do
  project 'ClickStreamHost/ClickStreamHost.xcodeproj'
  clickstream_pods
end

target 'ClickStreamHostTests' do
  project 'ClickStreamHost/ClickStreamHost.xcodeproj'
  clickstream_pods
end

target 'ClickStreamHostUITests' do
  project 'ClickStreamHost/ClickStreamHost.xcodeproj'
  clickstream_pods
end
