// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: raccoon.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc-swift` plugin that is newer than the version
// of the SwiftProtobuf library you're using. Please see the documentation for a
// temporary workaround:
//   https://github.com/apple/swift-protobuf/blob/main/Documentation/API.md

/// `platform` denotes the mobile client platform generating the event.
/// Example: ANDROID, IOS, FLUTTER
public enum Odpf_Raccoon_Platform: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// `PLATFORM_UNSPECIFIED` indicates the platform is not provided
  /// or cannot be determined. This is the default value.
  case unspecified // = 0

  /// `PLATFORM_ANDROID` indicates the event originated from
  /// an Android native application.
  case android // = 1

  /// `PLATFORM_IOS` indicates the event originated from
  /// an iOS native application.
  case ios // = 2

  /// `PLATFORM_FLUTTER` indicates the event originated from
  /// a Flutter-based application.
  case flutter // = 3

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .android
    case 2: self = .ios
    case 3: self = .flutter
    default: self = .unspecified
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .android: return 1
    case .ios: return 2
    case .flutter: return 3
    }
  }

  // The compiler won't synthesize support with the `UNRECOGNIZED` case.
  public static let allCases: [Odpf_Raccoon_Platform] = [
    .unspecified,
    .android,
    .ios,
    .flutter,
  ]
}

extension Odpf_Raccoon_Platform: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "PLATFORM_UNSPECIFIED"),
    1: .same(proto: "PLATFORM_ANDROID"),
    2: .same(proto: "PLATFORM_IOS"),
    3: .same(proto: "PLATFORM_FLUTTER"),
  ]
}
