//
//  HealthTrackerDTO.swift
//  Clickstream
//
//  Created by Abhijeet Mallick on 30/05/22.
//  Copyright © 2022 Gojek. All rights reserved.
//

import Foundation

/// Stream of Health events generated by Clickstream which a client can listen
public class HealthTrackerDTO {
    public internal(set) var eventName: String!
    public internal(set) var failureReason: String?
    public internal(set) var timeToConnection: Date?
    public internal(set) var eventGUIDs: [String]?
    public internal(set) var eventBatchGUIDs: [String]?
    public internal(set) var sessionID: String?
    public internal(set) var eventCount: Int?
    
    init() { }
}
