// Generated by the protocol buffer compiler.  DO NOT EDIT!
// clang-format off
// source: App.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AppRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface AppRoot : GPBRootObject
@end

#pragma mark - App

typedef GPB_ENUM(App_FieldNumber) {
  App_FieldNumber_Version = 1,
  App_FieldNumber_PackageName = 2,
};

/**
 *
 * Corresponds to the details for the app used by the user.
 **/
GPB_FINAL @interface App : GPBMessage

/**
 *
 * Version of the client app. Use this property to send version with every event.
 * This allows for segmentation based on the app version.
 * Sample values: "1.0.0", "1.0.1".
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *version;

/**
 *
 * Package name of the client app. Use this property to send package name with every event.
 * Sample values: "com.clickstream.app".
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *packageName;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
