// Generated by the protocol buffer compiler.  DO NOT EDIT!
// clang-format off
// source: User.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

#import "App.pbobjc.h"
#import "Device.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UserRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface UserRoot : GPBRootObject
@end

#pragma mark - User

typedef GPB_ENUM(User_FieldNumber) {
  User_FieldNumber_Guid = 1,
  User_FieldNumber_Name = 2,
  User_FieldNumber_Age = 3,
  User_FieldNumber_Gender = 4,
  User_FieldNumber_PhoneNumber = 5,
  User_FieldNumber_Email = 6,
  User_FieldNumber_App = 7,
  User_FieldNumber_Device = 8,
  User_FieldNumber_DeviceTimestamp = 9,
};

/**
 *
 * Corresponds to the details for the user.
 **/
GPB_FINAL @interface User : GPBMessage

/**
 *
 * Unique identy of the user.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *guid;

/**
 *
 * User's full name.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/**
 *
 * User's age.
 **/
@property(nonatomic, readwrite) int32_t age;

/**
 *
 * User's gender.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *gender;

/**
 *
 * User's phone number.
 **/
@property(nonatomic, readwrite) int64_t phoneNumber;

/**
 *
 * User's email address.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

/**
 *
 * User's app details.
 **/
@property(nonatomic, readwrite, strong, null_resettable) App *app;
/** Test to see if @c app has been set. */
@property(nonatomic, readwrite) BOOL hasApp;

/**
 *
 * User's device details.
 **/
@property(nonatomic, readwrite, strong, null_resettable) Device *device;
/** Test to see if @c device has been set. */
@property(nonatomic, readwrite) BOOL hasDevice;

/**
 *
 * Timestamp for the event.
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *deviceTimestamp;
/** Test to see if @c deviceTimestamp has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceTimestamp;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
