

default_platform(:ios)

platform :ios do
  
  desc "Lane to run the unit_tests."
  # Lane to run the unit_tests.
    lane :unit_test do

        update_cocoapods(repo_update: true)

        run_tests(
            workspace: "#{library_name}.xcworkspace",
            scheme: scheme_name,
            sdk: "iphonesimulator",
            clean: true,
            code_coverage: true,
            output_directory: "fastlane/reports",
            buildlog_path: "./build/tests_log",
            devices: TEST_SIMULATORS
        )
    end


  desc "Lane to publish code coverage."
  # Lane to publish code coverage.
    lane :update_cocoapods do |options|
        cocoapods(        
          try_repo_update_on_error: true,
          repo_update: options[:repo_update],
          podfile: "#{root_path}/Podfile", 
          error_callback: lambda { |result|
            if options[:retried]
                UI.user_error!("Failed to install cocoapods: \n #{result}")
            else
                sh('bundle exec pod repo remove trunk')
                options[:retried] = true
                update_cocoapods(options)
            end

          }
        )
    end

  def root_path
        Pathname.new(File.expand_path(Dir.pwd)).parent
  end

  def library_name
        "Clickstream"
  end

  def scheme_name 
        library_name
  end

  TEST_SIMULATORS = ["iPhone 8 Plus"]

end
