name: "Clickstream Bump Pod Version"

on:
  pull_request:
    branches: 
      - main
      - rename_sdk
    types: [closed]

# Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  bump-pod-version:
    name: "Version bump and push"
    if: ${{ github.event.pull_request.merged }}
    runs-on: macos-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: version bump
        run: python3 auto_version_bump.py
